CREATE DATABASE elitodo;

USE elitodo;
CREATE TABLE events (
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL
);


CREATE TABLE tickets (
  id INT(11) AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  closed BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE melee (
  id INT(11) AUTO_INCREMENT PRIMARY KEY,
  login VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  closed BOOLEAN NOT NULL DEFAULT false
);
